version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:5000
    depends_on:
      - redis
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
volumes:
  redis-data: